### ISSUE TITLE
套入後介面無中文化

### ISSUE THREAD

**Issue by Shironeko0o** [SmallYuanSY/LocalizeLimbusCompany_TW#10]
### 说说你遇到的问题？

套入後遊戲介面及劇情依然為英文想詢問是否是我套錯地方
![螢幕擷取畫面 2024-12-02 164804](https://github.com/user-attachments/assets/87118f10-9638-4d08-be3e-4bfa709aabd2)

**Comment by SmallYuanSY** [comment]
請重新看過教學或進入discord頻道中詢問，你的問題實在過於常見
