### ISSUE TITLE
5.10更新後反而變回英文

### ISSUE THREAD

**Issue by j7842610** [SmallYuanSY/LocalizeLimbusCompany_TW#3]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修復的情况

### 问题描述

更新最新版後，除了更新日誌是中文以及換畫面的loading顯示中文外，全部變回預設的英文
但是設定那裏仍然顯示語言為中文

### 日志文件

[Player(游戏日志).log](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/files/12267482/Player.log)

### 截图

![2023-08-05_223101](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/assets/141505389/860b304d-6365-4925-a8f5-349fd6658e5d)
![2023-08-05_223119](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/assets/141505389/ff7dec7c-9f88-488b-9f39-d31e7ba8fb95)
![2023-08-05_223132](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/assets/141505389/8c7d1049-cab1-4733-814f-764c149f56d9)
![2023-08-05_223150](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/assets/141505389/417bd708-95e1-4f86-a62c-f2e7a288924c)

**Comment by j7842610** [comment]
上面提供的遊戲日誌log是開著遊戲的時候，現在附的是關閉遊戲後

[Player(游戏日志).log](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/files/12267495/Player.log)

**Comment by SmallYuanSY** [comment]
大大 你DC是哪位 我幫你處理一下

**Comment by j7842610** [comment]
丁子

**Comment by SmallYuanSY** [comment]
你有加DC群嗎?

**Comment by j7842610** [comment]
有加入，但顯示沒有權限發言

**Comment by j7842610** [comment]
我看到有新的更新了，我再去試試
謝謝！

**Comment by SmallYuanSY** [comment]
你有看到規則嗎?

**Comment by j7842610** [comment]
已看完DC群，且問題已解決
非常感謝
