### ISSUE TITLE
漢化

### ISSUE THREAD

**Issue by TYALAKB050921** [SmallYuanSY/LocalizeLimbusCompany_TW#7]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修復的情况

### 问题描述

劇情還是英文和出現口口口

### 日志文件

[Latest(框架日誌).log](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/files/13453730/Latest.log)
[Player(遊戲日誌).log](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/files/13453732/Player.log)

### 截图

![image](https://github.com/SmallYuanSY/LocalizeLimbusCompany_TW/assets/151884260/d50d5621-dcab-4fa2-bb07-9b92e669abc7)

**Comment by SmallYuanSY** [comment]
劇情現在就是壞的 可以先在群裡先問大家 不用直接回應
