### ISSUE TITLE
翻譯失效

### ISSUE THREAD

**Issue by kiljj** [SmallYuanSY/LocalizeLimbusCompany_TW#9]
### 在提问之前...

- [X] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [x] 我已查看最新测试版本的更新内容，并未提及该 bug 已被修復的情况

### 问题描述

因未知原因
除:
過場動畫(如:正在清潔座椅......)
戰鬥小貼士
翻譯完全失效

### 日志文件

[Latest(框架日誌).log](https://github.com/user-attachments/files/17239183/Latest.log)
[Player(遊戲日誌).log](https://github.com/user-attachments/files/17239184/Player.log)

### 截图

![1](https://github.com/user-attachments/assets/5b589cd2-97d3-4dfb-a2e9-7ca3ce3c7e45)
![2](https://github.com/user-attachments/assets/6df1543c-2703-43ed-906a-a44c3666ab5f)
![3](https://github.com/user-attachments/assets/39c3b0d3-bebe-4f3c-bc73-a7902f859776)
![4](https://github.com/user-attachments/assets/04386d01-2d46-4014-96cf-cb02d3a57d75)
![5](https://github.com/user-attachments/assets/e7a23692-157e-47e3-8465-5a738ea86d3b)
![6](https://github.com/user-attachments/assets/eac75b22-c024-4b21-97d2-b5406d1fdd24)
![7](https://github.com/user-attachments/assets/d4ae0527-d777-47d1-ac8e-43f958d8b345)
![8](https://github.com/user-attachments/assets/286843f6-07d0-4535-a067-31a4170f094b)
![9](https://github.com/user-attachments/assets/38997445-9fdb-4d91-98bc-84784a67f111)
![10](https://github.com/user-attachments/assets/79cd13f1-7d25-4721-9420-1c811896201a)
![11](https://github.com/user-attachments/assets/d35df412-12c2-4a0a-a871-b67498671c0e)

### 还有别的吗？

win10

**Comment by Oofer123-cmyk** [comment]
我的也是這樣

**Comment by Ss13625789ismypassword** [comment]
我也一樣

**Comment by kiljj** [comment]
現在好像是完全失效了
之前應該是月計改了文案的位置
現在應該是打外掛時誤殺了

**Comment by kiljj** [comment]
各位
在下用steam重新下載後
重裝.NET 6.0 SDK和BepInEx之後就好了
詳細步驟是
1.進入steam
2.![螢幕擷取畫面 2024-10-05 160152](https://github.com/user-attachments/assets/8b0631e9-773d-4892-a924-47f94f06e197)
3.![螢幕擷取畫面 2024-10-05 160214](https://github.com/user-attachments/assets/4771aebe-eedb-4d4d-b898-fe7b8222a515)
4.![螢幕擷取畫面 2024-10-05 160240](https://github.com/user-attachments/assets/047618b0-7330-4162-bf55-94271c7b5892)
5.重裝.NET 6.0 SDK和BepInEx和漢化
6.打開遊戲
ex.如果依舊失敗的話先重啟電腦，再開一次

**Comment by SmallYuanSY** [comment]
抱歉各位 我最近github上面沒顯示你們的訊息 月計改動了源代碼 已經有把更新上傳
